export const MIXING_CONFIG = {
  SERVICE_FEE: 0.015,
  NETWORK_FEE: 0.0001,
  MIN_AMOUNT: 0.001,
  MAX_AMOUNT: 100,
  MAX_OUTPUTS: 5,
  MIN_OUTPUTS: 2,
  MAX_DELAY_HOURS: 24,
  MIN_DELAY_HOURS: 0.5,
  CONFIRMATIONS_REQUIRED: 3,
} as const;
