export const MIXING_CONTENT = {
  title: "Mixer",
  subtitle: "Configure your mixing transaction.",
  amountLabel: "Amount (BTC)",
  amountPlaceholder: "0.00000000",
  destinationsTitle: "Destination Addresses",
  addButton: "Add",
  destinationLabel: "Destination",
  addressPlaceholder: "Destination BTC address",
  invalidAddress: "Invalid address",
  percentageLabel: "Percentage",
  delayLabel: "Delay",
  distributionWarning: "Total distribution: {total}% (must be 100%)",
  summaryTitle: "Transaction Summary",
  summaryAmount: "Amount:",
  summaryServiceFee: "Service fee (1.5%):",
  summaryNetworkFee: "Network fee:",
  summaryReceived: "Total received:",
  confirmButton: "Confirm Mixing",
} as const;
