export const MIXING_CONTENT = {
  title: "Mixer",
  subtitle: "Configure sua transação de mixing.",
  amountLabel: "Valor (BTC)",
  amountPlaceholder: "0.00000000",
  destinationsTitle: "Endereços de Destino",
  addButton: "Adicionar",
  destinationLabel: "Destino",
  addressPlaceholder: "Endereço BTC de destino",
  invalidAddress: "Endereço inválido",
  percentageLabel: "Porcentagem",
  delayLabel: "Delay",
  distributionWarning: "Distribuição total: {total}% (deve ser 100%)",
  summaryTitle: "Resumo da Transação",
  summaryAmount: "Valor:",
  summaryServiceFee: "Taxa de serviço (1.5%):",
  summaryNetworkFee: "Taxa de rede:",
  summaryReceived: "Total recebido:",
  confirmButton: "Confirmar Mixing",
} as const;
